SELECT TOP (100) [CountryID]
,[Country]
,[Year]
,[AMA_exchange_rate]
,[IMF_based_exchange_rate]
,[Population]
,[Currency]
,[Per_capita_GNI]
,[Agriculture_hunting_forestry_fishing_ISIC_AB]
,[Changes_in_inventories]
,[Construction_ISIC_F]
,[Exports_of_goods_and_services]
,[Final_consumption_expenditure]
,[General_government_final_consumption_expenditure]
,[Gross_capital_formation]
,[Gross_fixed_capital_formation_including_Acquisitions_less_disposals_of_valuables]
,[Household_consumption_expenditure_including_Non_profit_institutions_serving_households]
,[Imports_of_goods_and_services]
,[Manufacturing_ISIC_D]
,[Mining_Manufacturing_Utilities_ISIC_C_E]
,[Other_Activities_ISIC_J_P]
,[Total_Value_Added]
,[Transport_storage_and_communication_ISIC_I]
,[Wholesale_retail_trade_restaurants_and_hotels_ISIC_G_H]
,[Gross_National_Income_GNI_in_USD]
,[Gross_Domestic_Product_GDP]
 FROM [GlobaleconomyDB].[dbo].[indicators]